# fly.toml app configuration file generated for docker-bot on 2024-09-20T11:58:37-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docker-bot'
primary_region = 'sea'

[build]

[env]
  FLY_APP_NAME = 'docker-bot'

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = "shared-cpu-2x"
  memory = "1gb"

