# fly.toml app configuration file generated for docker-bot-misty-wildflower-9137 on 2024-12-09T15:07:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docker-bot-misty-wildflower-9137'
primary_region = 'sea'

[build]

[env]
  FLY_APP_NAME = 'docker-bot'

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'performance-4x'
  memory = '8gb'
